### ISSUE TITLE
Shortcodes are removed from the breadcrumb.

### ISSUE THREAD

**Issue by shazahm1** [Mr2P/breadcrumb-block#3]
Please see my comment:

- https://github.com/Mr2P/breadcrumb-block/commit/a4c40acece0b735798770e281fa57a2221273967#r124785928

**Comment by Mr2P** [comment]
@shazahm1 If you want to display shortcodes in the breadcrumb, you can add a hook to the filter `breadcrumb_block_get_breadcrumb_trail` for now. For example:
`add_filter( 'breadcrumb_block_get_breadcrumb_trail', function ($breadrumb) { return do_shortcode($breadcrumb); } );`
I've tested your pull request, it did not work with breadcrumb in the site editor, so I'll find another solution for it later.

**Comment by shazahm1** [comment]
Sorry, but I think you misunderstood...

I do not want to expand (do_shortcode) the shortcode. The code change in the pull request made sure the shortcode did not run, but instead displayed the actual shortcode.

Here's an example breadcrumb. Notice that the shortcode tab and brackets are displayed in the breadcrumb. Previous to the pull request, the shortcode would be run (do_shortcode); now, the latest update removes the shortcode. The pull request entity encoded the shortcode brackets so it would show the tag in the breadcrumb, as shown in the example.

- https://connections-pro.com/documentation/shortcodes/cn-content/

![2023-08-21_09-51-27](https://github.com/Mr2P/breadcrumb-block/assets/1185008/065107b5-0ff6-4163-a013-f521a729e44d)

**Comment by Mr2P** [comment]
Ah yeah, I misunderstood. But in this case, I think you should add a filter for your need for now. Something like: 
```
add_filter( 'breadcrumb_block_get_breadcrumb_trail', function ($breadrumb) { 
  // Ensure shortcode brackets ae HTML entity encoded, so shortcodes are not ran if they exist in breadcrumb name.
  $replace = array(
    '[' => '&#91;',
    ']' => '&#93;',
  );

  return str_replace( array_keys( $replace ), array_values( $replace ), $breadcrumb );
);
```
I copied it from your pull request.

**Comment by shazahm1** [comment]
Darnit :) yes, I should have simply used the filter to begin with. Thanks for your time!
